version: '0.1'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
#    volumes:
#      - ./instance:/app/instance
#      - ./data:/app/data
#    environment:
#      - FLASK_ENV=production
#      - PYTHONPATH=/app
#    command: >
#      sh -c "python -m prepare || python -m run"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - backend
#    environment:
#      - REACT_APP_API_URL=http://localhost:5000